language: php

php:
    - 5.6
    - 7.0

branches:
  only:
    - 1.x.x-dev
    - 2.x.x-dev
    - master

install:
    - composer install

script:
    - mkdir -p build/logs
    - php vendor/bin/phpunit -c phpunit.xml.dist

after_success:
    - travis_retry php vendor/bin/coveralls